### ISSUE TITLE
Update - Meta

### ISSUE THREAD

**Issue by AbdellaToronto** [rangle/ngCourse2#937]
### Meta
- [ ] plnkr links need updating. Code is there but does not run
- [ ] should it be referred to Angular book (vs. Angular 2) ?
- [ ] NodeJS should be renamed to Node.js
